// This file was auto-generated by ".\Create-SphereShaders.ps1 -OutPath . -ResourceStart 1000" on 11/28/2023 18:30:37
#define TRI_INST (1)
#define PER_VERTEX_INTENSITY (1)
#define RAYCASTING (1)
#define INSTANCING (1)
#include "SpherePixelShaderCore.hlsli"
