// This file was auto-generated by ".\Create-SphereShaders.ps1 -OutPath . -ResourceStart 1000" on 11/28/2023 18:30:37
#define ADAPT_POLY_TESS (1)
#define PER_VERTEX_RADIUS (1)
#define PER_PIXEL_INTENSITY (1)
#define PER_VERTEX_RAY (1)
#define RAYCASTING (1)
#include "SphereHullShaderCore.hlsli"
