// This file was auto-generated by ".\Create-SphereShaders.ps1 -OutPath . -ResourceStart 1000" on 11/28/2023 18:30:37
#define HEMISPHERE_TESS (1)
#define PER_VERTEX_COLOUR (1)
#include "SphereVertexShaderCore.hlsli"
