// This file was auto-generated by ".\Create-SphereShaders.ps1" on 11/27/2023 18:38:49
#define QUAD_TESS (1)
#define PER_VERTEX_COLOUR (1)
#define RAYCASTING (1)
#include "SphereDomainShaderCore.hlsli"
