// This file was auto-generated by ".\Create-SphereShaders.ps1 -OutPath . -ResourceStart 1000" on 05/31/2022 14:40:39
#define QUAD_INST (1)
#define PER_VERTEX_COLOUR (1)
#define FLOAT_COLOUR (1)
#define PER_VERTEX_RADIUS (1)
#define RAYCASTING (1)
#define INSTANCING (1)
#include "SpherePixelShaderCore.hlsli"
