// This file was auto-generated by ".\Create-SphereShaders.ps1" on 11/27/2023 18:38:49
#define TRI_INST (1)
#define PER_VERTEX_INTENSITY (1)
#define RAYCASTING (1)
#define INSTANCING (1)
#include "SpherePixelShaderCore.hlsli"
