// This file was auto-generated by ".\Create-SphereShaders.ps1 -OutPath . -ResourceStart 1000" on 06/17/2022 22:47:53
#define ADAPT_HEMISPHERE_TESS (1)
#define PER_VERTEX_RADIUS (1)
#define PER_PIXEL_INTENSITY (1)
#include "SphereVertexShaderCore.hlsli"
