// This file was auto-generated by ".\Create-SphereShaders.ps1 -OutPath . -ResourceStart 1000" on 05/31/2022 14:40:39
#define ADAPT_HEMISPHERE_TESS (1)
#define PER_VERTEX_RADIUS (1)
#include "SphereHullShaderCore.hlsli"
