// This file was auto-generated by ".\Create-SphereShaders.ps1 -OutPath . -ResourceStart 1000" on 11/28/2023 18:30:37
#define STPA (1)
#define PER_VERTEX_RADIUS (1)
#define RAYCASTING (1)
#include "SphereGeometryShaderCore.hlsli"
