// This file was auto-generated by ".\Create-SphereShaders.ps1 -OutPath . -ResourceStart 1000" on 05/31/2022 14:40:39
#define QUAD_TESS (1)
#define PER_VERTEX_RAY (1)
#define RAYCASTING (1)
#include "SphereHullShaderCore.hlsli"
