// This file was auto-generated by ".\Create-SphereShaders.ps1 -OutPath . -ResourceStart 1000" on 05/31/2022 14:40:39
#define POLY_TESS (1)
#define PER_PIXEL_INTENSITY (1)
#define RAYCASTING (1)
#include "SphereVertexShaderCore.hlsli"
