// This file was auto-generated by ".\Create-SphereShaders.ps1 -OutPath . -ResourceStart 1000" on 06/17/2022 22:47:53
#define QUAD_INST (1)
#define PER_VERTEX_COLOUR (1)
#define PER_VERTEX_RADIUS (1)
#define RAYCASTING (1)
#define INSTANCING (1)
#include "SphereVertexShaderCore.hlsli"
