// This file was auto-generated by ".\Create-SphereShaders.ps1" on 11/27/2023 18:38:49
#define ADAPT_HEMISPHERE_TESS (1)
#define PER_VERTEX_COLOUR (1)
#define PER_VERTEX_RADIUS (1)
#include "SpherePixelShaderCore.hlsli"
