// This file was auto-generated by ".\Create-SphereShaders.ps1" on 11/27/2023 18:38:49
#define TRI_INST (1)
#define PER_VERTEX_COLOUR (1)
#define FLOAT_COLOUR (1)
#define PER_VERTEX_RADIUS (1)
#define PER_VERTEX_RAY (1)
#define RAYCASTING (1)
#define INSTANCING (1)
#include "SphereVertexShaderCore.hlsli"
