#
# azure-pipelines.yml
#
# Copyright © 2022 Visualisierungsinstitut der Universität Stuttgart. Alle Rechte vorbehalten.
#

trigger:
- master

schedules:
- cron: '0 12 * * 0'
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

variables:
  cmakeDefines: >-
     -DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)\$(platform)\$(configuration)
     -DBUILD_TESTING=OFF
     -DSPDLOG_BUILD_EXAMPLES=OFF
     -DTRROJAN_DEBUG_OVERLAY=OFF
     -DTRROJAN_WITH_DSTORAGE=OFF

jobs:
- job: Windows
  strategy:
    matrix:
      'Win32 Debug':
        platform: Win32
        configuration: Debug
        generator: 'Visual Studio 16 2019'
      'Win32 Release':
        platform: Win32
        configuration: Release
        generator: 'Visual Studio 16 2019'
      'Win64 Debug':
        platform: x64
        configuration: Debug
        generator: 'Visual Studio 16 2019'
      'Win64 Release':
        platform: x64
        configuration: Release
        generator: 'Visual Studio 16 2019'
  pool:
    name: 'hardware'
    demands:
    - cmake
    - VisualStudio_16.0

  steps:
  - task: CMake@1
    inputs:
      workingDirectory: $(Build.SourcesDirectory)
      cmakeArgs: '.. -G"$(generator)" -A"$(platform)" -S"$(Build.SourcesDirectory)" -B"$(Build.SourcesDirectory)\$(platform)\$(configuration)" $(cmakeDefines)'
  - task: MSBuild@1
    inputs:
        solution: '$(Build.SourcesDirectory)\$(platform)\$(configuration)\ALL_BUILD.vcxproj'
        maximumCpuCount: true
        configuration: $(configuration)
        platform: $(platform)
