// This file was auto-generated by ".\Create-SphereShaders.ps1 -OutPath . -ResourceStart 1000 -ResourcePath "trrojand3d12\d3d12"" on 11/28/2023 19:07:27
#define GEO_POLY (1)
#define RAYCASTING (1)
#define SHADER_ROOT_SIGNATURE\
    "RootFlags(ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT),"\
    "DescriptorTable(CBV(b0), CBV(b1), CBV(b2), visibility=SHADER_VISIBILITY_ALL)"
#include "SphereVertexShaderCore.hlsli"
