// This file was auto-generated by ".\Create-SphereShaders.ps1" on 11/27/2023 18:57:10
#define TRI_INST (1)
#define PER_VERTEX_RAY (1)
#define RAYCASTING (1)
#define INSTANCING (1)
#define SHADER_ROOT_SIGNATURE\
    "RootFlags(ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT),"\
    "DescriptorTable(SRV(t0), visibility = SHADER_VISIBILITY_VERTEX),"\
    "DescriptorTable(CBV(b0), CBV(b1), CBV(b2), visibility=SHADER_VISIBILITY_ALL)"
#include "SpherePixelShaderCore.hlsli"
